# Generated by Django 4.0.3 on 2022-03-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_event_news_video_rename_subscribers_subscriber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_video',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
